import type { CardConfig } from "@/types";

export const CARD_SIZES = {
  portrait: { w: 450, h: 600 },
  landscape: { w: 600, h: 450 },
};

export const TEMPLATES: Record<string, CardConfig> = {
  "Project Card": {
    size: CARD_SIZES.landscape,
    prettyName: "Example Project",
    tagline: "A short, punchy subtitle",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis urna sit amet lorem ullamcorper porttitor. Ut tempor semper euismod. Integer ornare risus eget erat.",
    techStack: "React, TypeScript, Vite",
    status: "Active",
    githubUrl: "https://github.com/leo-alvarenga",
    author: "leo-alvarenga",
    orientation: "landscape",
    bgColor: "#0d1117",
    textColor: "#e6edf3",
    accentColor: "#58a6ff",
    font: "Inter",
    borderWidth: 2,
    borderRadius: 8,
    bgPattern: "none",
  },
  "Github Profile Readme Banner": {
    status: "",
    author: "",
    githubUrl: "",
    techStack: "",
    description: "",

    font: "Inter",
    borderWidth: 4,
    borderRadius: 16,
    bgPattern: "none",
    bgColor: "#0d1117",
    textColor: "#e6edf3",
    orientation: "custom",
    accentColor: "#58a6ff",
    prettyName: "Hi, I'm John Doe",
    tagline: "Software Engineer @ Acme Inc.",

    size: {
      w: 800,
      h: 200,
    },
  },
  "Open Source Library": {
    size: CARD_SIZES.landscape,
    prettyName: "my-awesome-lib",
    tagline: "Zero-dependency, tree-shakeable utility library",
    description: "A lightweight library that does one thing and does it well. Works in Node, Deno, and the browser.",
    techStack: "TypeScript, Rollup, Vitest",
    status: "Active",
    githubUrl: "https://github.com/leo-alvarenga",
    author: "leo-alvarenga",
    orientation: "landscape",
    bgColor: "#0d1117",
    textColor: "#e6edf3",
    accentColor: "#3fb950",
    font: "Space Grotesk",
    borderWidth: 2,
    borderRadius: 12,
    bgPattern: "waves",
  },
  "Portfolio Piece": {
    size: CARD_SIZES.portrait,
    prettyName: "My Portfolio Project",
    tagline: "Built to learn, shipped to impress",
    description: "A full-stack web app showcasing modern React patterns, type-safe APIs, and CI/CD pipelines deployed on Vercel.",
    techStack: "Next.js, tRPC, Prisma",
    status: "Active",
    githubUrl: "https://github.com/leo-alvarenga",
    author: "leo-alvarenga",
    orientation: "portrait",
    bgColor: "#ffffff",
    textColor: "#1a1a2e",
    accentColor: "#7c3aed",
    font: "Inter",
    borderWidth: 2,
    borderRadius: 16,
    bgPattern: "organic",
  },
  "CLI Tool": {
    size: CARD_SIZES.landscape,
    prettyName: "my-cli",
    tagline: "$ do-the-thing --fast --no-regrets",
    description: "A fast, opinionated CLI that automates the boring parts of your workflow. Install once, save hours weekly.",
    techStack: "Go, Cobra, Bubble Tea",
    status: "Active",
    githubUrl: "https://github.com/leo-alvarenga",
    author: "leo-alvarenga",
    orientation: "landscape",
    bgColor: "#0c0c0c",
    textColor: "#d4d4d4",
    accentColor: "#00ff88",
    font: "Fira Code",
    borderWidth: 1,
    borderRadius: 4,
    bgPattern: "cyberpunk",
  },
  "WIP / Hackathon": {
    size: CARD_SIZES.landscape,
    prettyName: "Project Codename",
    tagline: "48 hours to ship something that matters",
    description: "Hackathon project. Rough edges expected. The idea is solid, the deadline is not.",
    techStack: "TBD",
    status: "WIP",
    githubUrl: "https://github.com/leo-alvarenga",
    author: "leo-alvarenga",
    orientation: "landscape",
    bgColor: "#1a1200",
    textColor: "#fef3c7",
    accentColor: "#f59e0b",
    font: "JetBrains Mono",
    borderWidth: 3,
    borderRadius: 8,
    bgPattern: "canvas",
  },
};

export const DEFAULT_CONFIG: CardConfig = {
  size: CARD_SIZES.landscape,
  prettyName: "Example Project",
  tagline: "A short, punchy subtitle",
  description:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis urna sit amet lorem ullamcorper porttitor. Ut tempor semper euismod. Integer ornare risus eget erat.",
  techStack: "React, TypeScript, Vite",
  status: "Active",
  githubUrl: "https://github.com/leo-alvarenga",
  author: "leo-alvarenga",
  orientation: "landscape",
  bgColor: "#0d1117",
  textColor: "#e6edf3",
  accentColor: "#58a6ff",
  font: "Inter",
  borderWidth: 2,
  borderRadius: 8,
  bgPattern: "cyberpunk",
};
